var number1 = 35;
var number2 = 40;
var number3 = 10;
var numberAdd = number1 + number2 + number3;
var numberSubtract = number2 - number1;
console.log(numberAdd);
console.log(numberSubtract);
var numberMultiply = numberAdd * numberSubtract;
console.log(numberMultiply);
var numberDivide = numberMultiply;
//compersion Operators
var comp1 = numberDivide == 100;
console.log(comp1);
var comp2 = numberDivide != 100;
console.log(comp2);
var comp3 = numberDivide > 100;
console.log(comp3);
var comp4 = numberDivide < 100;
console.log(comp4);
var comp5 = numberDivide >= 100;
console.log(comp5);
var comp6 = numberDivide <= 100;
console.log(comp6);
//concatenation:
console.log("concatenation");
var name1 = "ruqaiya";
var name2 = "gull";
var Fullname = name1 + " " + name2;
console.log(Fullname);
var num1 = 10;
var idName = name1 + num1;
console.log(idName);
var num2 = "46";
var idNumber = num1 + num2;
console.log(idNumber);
var w = 50;
w += 5;
console.log(w);
var s = 60;
s -= 30;
console.log(s);
